stages:
  - build
  - release

variables:
  BANANACTL: bananactl
  BANANADM: bananadm

build-stack:
  stage: build
  image: docker/compose:1.25.0-rc1
  services:
    - docker:dind
  script: docker-compose build && docker-compose push

.build-agent: &build-agent
  stage: build
  variables:
    GOPATH: /builds/products/banana/agent
  image:
    name: enix/go-dep:0.5
    entrypoint:
      - sh
      - -c
  script:
    - cd agent
    - dep init
    - go build ./src -o ${BANANACTL}
  artifacts:
    paths:
      - ${BANANACTL}

build-agent-linux:
  <<: *build-agent
  variables:
    GOOS: linux

build-agent-darwin:
  <<: *build-agent
  variables:
    GOOS: darwin

build-agent-windows:
  <<: *build-agent
  variables:
    GOOS: windows
