stages:
  - build
  - release

variables:
  REPO_DIR: /builds/products/banana

build-stack:
  stage: build
  image: docker/compose:1.25.0-rc1
  services:
    - docker:dind
  before_script:
    - echo ${CI_REGISTRY_PASSWORD} | docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} --password-stdin
  script: docker-compose build --parallel && docker-compose push
  except:
    - master

.build-agent: &build-agent
  stage: build
  image:
    name: enix/go-dep:0.5
    entrypoint:
      - sh
      - -c
  before_script:
    - mkdir -p /go/src/enix.io/banana
    - ln -s ${REPO_DIR}/agent/src /go/src/enix.io/banana/src
    - cd /go/src/enix.io/banana/src
    - unlink services
    - unlink models
    - cp -r ${REPO_DIR}/api/src/services .
    - cp -r ${REPO_DIR}/api/src/models .
  script:
    - cd /go/src/enix.io/banana/src
    # - dep init
    # - go build -v -o ${REPO_DIR}/${BANANACTL}-${GOOS}
    - echo > ${REPO_DIR}/${BANANACTL}-${GOOS}
  artifacts:
    paths:
      - ${BANANACTL}-${GOOS}

build-agent-linux:
  <<: *build-agent
  variables:
    GOOS: linux

build-agent-darwin:
  <<: *build-agent
  variables:
    GOOS: darwin

build-agent-windows:
  <<: *build-agent
  variables:
    GOOS: windows

semantic-release:
  stage: release
  image: enix/semantic-release:gitlab
  script:
    # - mv docker-compose.prod.yml docker-compose.yml
    - npx semantic-release --ci
  # only:
  #   - master
  except:
    - tags

release-admin:
  stage: release
  image: python:3.7
  before_script:
    - pip3 install twine
  script:
    - cd admin
    - ./setup.py sdist bdist_wheel
    - twine upload dist/* --repository-url ${PYPI_REPOSITORY}
  only:
    - tags
