stages:
  - build
  - release

variables:
  BANANACTL: bananactl
  BANANADM: bananadm

build-stack:
  stage: build
  image: docker/compose:1.25.0-rc1
  services:
    - docker:dind
  before_script:
    - echo ${CI_REGISTRY_PASSWORD} | docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} --password-stdin
  script: docker-compose build && docker-compose push

.build-agent: &build-agent
  stage: build
  image:
    name: enix/go-dep:0.5
    entrypoint:
      - sh
      - -c
  script:
    - export GOPATH=/builds/products/banana/agent
    - cd agent
    - dep init
    - go build ./src -o ${BANANACTL}
  artifacts:
    paths:
      - ${BANANACTL}

build-agent-linux:
  <<: *build-agent
  variables:
    GOOS: linux

build-agent-darwin:
  <<: *build-agent
  variables:
    GOOS: darwin

build-agent-windows:
  <<: *build-agent
  variables:
    GOOS: windows
