stages:
  - build
  - release

variables:
  BANANACTL: bananactl
  BANANADM: bananadm

build-stack:
  stage: build
  image: docker/compose
  services:
    - dind
  script: docker-compose build && docker-compose push

.build-agent: &build-agent
  stage: build
  image: enix/go-dep:0.5
  before_script:
    - mkdir dist
  script:
    - cd agent
    - go build -o ${BANANACTL}
  artifacts:
    paths:
      - ${BANANACTL}

build-agent-linux:
  <<: *build-agent
  variables:
    GOOS: linux

build-agent-darwin:
  <<: *build-agent
  variables:
    GOOS: darwin

build-agent-windows:
  <<: *build-agent
  variables:
    GOOS: windows
