plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/github'
    - repositoryUrl: https://github.com/enix/banana.git
      assets:
        - ./bananagent-*
        - ./docker-compose.yml
  - - '@semantic-release/gitlab'
    - gitlabUrl: https://gitlab.enix.io
      assets:
        - ./bananagent-*
        - ./docker-compose.yml
