plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/gitlab'
    - gitlabUrl: https://gitlab.enix.io
      assets:
        - ./bananactl-*
        - ./docker-compose.yml
