version: "3.4"

services:
  client:
    image: docker-registry.enix.io/products/banana/client:dev
    build:
      context: ./client
      target: bundler
    expose:
      - 80
    volumes:
      - ./client/src:/app/src
      - ./client/res/public:/app/public
      - ./client/config-overrides.js:/app/config-overrides.js
    restart: unless-stopped

  api:
    image: docker-registry.enix.io/products/banana/api:dev
    build:
      context: ./api
    ports:
      - 8080:80
    expose:
      - 80
    volumes:
      - ./api/src:/go/src/enix.io/banana/src
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWD=

  vault:
    image: vault:latest
    ports:
      - 7777:7777
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:7777
      - VAULT_DEV_ROOT_TOKEN_ID=myroot

  proxy:
    image: nginx:latest
    ports:
      - 443:443
    restart: unless-stopped
    volumes:
      - ./proxy:/etc/nginx/conf.d
      - ./security:/security

  redis:
    image: redis:5.0
    restart: unless-stopped
    # volumes:
    #   - ./db:/db
