version: "3.4"

services:
  client:
    image: docker-registry.enix.io/products/banana/client:dev
    build:
      context: ./client
      target: bundler
    expose:
      - 80
    volumes:
      - ./client/src:/app/src
      - ./client/res/public:/app/public
      - ./client/config-overrides.js:/app/config-overrides.js
    restart: unless-stopped

  api:
    image: docker-registry.enix.io/products/banana/api:dev
    build:
      context: ./api
    ports:
      - 8080:80
    expose:
      - 80
    volumes:
      - ./api/src:/go/src/enix.io/banana/src
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWD=

  vault:
    image: vault:latest
    command:
      - sh
      - -c
      - mkdir -p /data && chown vault:vault /data && vault server -config /config/vault.hcl
    restart: unless-stopped
    ports:
      - 7777:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config/vault:/config
      - ./config/tls:/tls

  proxy:
    image: nginx:latest
    ports:
      - 443:443
    restart: unless-stopped
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/tls:/tls
      - ./security/ca/trusted-ca.pem:/trusted-ca.pem

  redis:
    image: redis:5.0
    restart: unless-stopped
    # volumes:
    #   - ./db:/db
