version: "3.4"

services:
  ui:
    image: docker-registry.enix.io/products/banana/ui:${CI_COMMIT_TAG:-dev}
    build:
      context: ./ui
      target: bundler
    expose:
      - 80
    volumes:
      - ./ui/src:/app/src
      - ./ui/res/public:/app/public
      - ./ui/config-overrides.js:/app/config-overrides.js
    restart: unless-stopped

  api:
    image: docker-registry.enix.io/products/banana/api:${CI_COMMIT_TAG:-dev}
    build: ./api
    expose:
      - 80
    volumes:
      - ./api/src:/go/src/enix.io/banana/src
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWD=

  settings:
    image: docker-registry.enix.io/products/banana/settings:${CI_COMMIT_TAG:-dev}
    build: ./config
    restart: unless-stopped
    volumes:
      - settings:/settings

  vault:
    image: vault:1.1.3
    restart: unless-stopped
    command: /settings/vault/entrypoint.sh
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault:/data
      - settings:/settings

  nginx:
    image: docker-registry.enix.io/products/banana/nginx:${CI_COMMIT_TAG:-dev}
    build:
      context: ./config
      dockerfile: nginx/Dockerfile
    ports:
      - 443:443
    restart: unless-stopped

  redis:
    image: redis:5.0
    restart: unless-stopped
    volumes:
      - db:/data

volumes:
  db:
  vault:
  settings: