version: "3.4"

services:
  client:
    image: docker-registry.enix.io/products/banana/client:prod
    build:
      context: ./client
    ports:
      - 3000:80
    restart: unless-stopped

  api:
    image: docker-registry.enix.io/products/banana/api:prod
    build:
      context: ./api
      target: prod
    ports:
      - 8080:80
    restart: unless-stopped
