#! /usr/bin/env bash

target="prod"
project="banana"
path="$(dirname $0)"

if [ $# -lt 1 ]
then
  cmd="up -d --build"
else
  cmd="$@"
fi

exec="docker-compose                      \
  -p ${project}                           \
  -f ${path}/docker-compose.yml           \
  -f ${path}/docker-compose.${target}.yml \
  ${cmd}"

echo + ${exec}
echo

${exec}
