version: "3.4"

services:
  client:
    image: docker-registry.enix.io/products/banana/client:${CI_COMMIT_TAG}
    restart: unless-stopped
    expose:
      - 80

  api:
    image: docker-registry.enix.io/products/banana/api:${CI_COMMIT_TAG}
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWD=
      - GIN_MODE=release
    expose:
      - 80

  vault:
    image: docker-registry.enix.io/products/banana/vault:${CI_COMMIT_TAG}
    restart: unless-stopped
    ports:
      - 7777:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault:/data

  nginx:
    image: docker-registry.enix.io/products/banana/nginx:${CI_COMMIT_TAG}
    restart: unless-stopped
    ports:
      - 443:443

  redis:
    image: redis:5.0
    restart: unless-stopped
    volumes:
      - db:/data

volumes:
  - db:
  - vault:
