#! /usr/bin/env bash

set -e

function checkWarnings {
	if [ -s /tmp/banana-errors ]; then
		>&2 echo "warnings were found in backup logs"
		rm -f /tmp/banana-errors
		exit 1
	fi

	rm -f /tmp/banana-errors
}

case $1 in

version)
	echo v1.0.0
	;;

backup)
	>&2 duplicity $2 -v4 --log-fd 3 "${@:4}" $3 3> >(grep WARNING > /tmp/banana-errors)
	checkWarnings
	;;

restore)
	>&2 duplicity -v4 --log-fd 3 --restore-time $2 $3 "${@:4}" 3> >(grep WARNING > /tmp/banana-errors)
	checkWarnings
	;;

esac
