#! /usr/bin/env bash

set -e
storageUrl="s3://$3/$4/$5"

echo $storageUrl >&2

function checkWarnings {
	if [ -s /tmp/banana-errors ]; then
		>&2 echo "warnings were found in backup logs"
		rm -f /tmp/banana-errors
		exit 1
	fi

	rm -f /tmp/banana-errors
}

function generateMetadata {
	while read -r line; do
		key=$(echo "${line}" | sed -E 's/([a-zA-Z]*).*/\1/')
		value=$(echo "${line}" | sed -E 's/[^ ]* *(.*)/\1/')

		if [ ! -z ${key} ]; then local ${key}="${value}"; fi
	done

	jq -n \
		--argjson size $(echo ${TotalDestinationSizeChange} | awk '{printf $1}') \
		'{ size: $size }'
}

function cleanLogs {
	grep -v '^A ' | grep -v '^M ' | grep -v '^D ' >&2
}

function generateArtifacts {
	cat | gzip >&3
}

case $1 in

version)
	echo v1.0.0
	;;

backup)
	duplicity $2 -v5 --log-fd 3 "${@:6}" ${storageUrl} 3> >(grep WARNING > /tmp/banana-errors) \
	| tee >(generateMetadata) >(generateArtifacts) >(cleanLogs) >/dev/null
	checkWarnings
	;;

restore)
	>&2 duplicity -v5 --log-fd 3 --restore-time $2 ${storageUrl} "${@:6}" 3> >(grep WARNING > /tmp/banana-errors)
	checkWarnings
	;;

esac
