#! /usr/bin/env bash

storageUrl="s3://$3/$4/$5"
tempFile="/tmp/mysqldump.sql"
defaultArgs="--quote-names --quick --add-drop-table --add-locks --allow-keywords --disable-keys --extended-insert --single-transaction --create-options --comments --net_buffer_length=16384"
dockerExec=""
# dockerExec="docker exec -ie MYSQL_PWD=${MYSQL_PWD} mysql"

rm -f ${tempFile} ${tempFile}.gzip

case $1 in

version)
	echo v1.0.0 "(mysqldump v$(${dockerExec} mysqldump --version | awk '{printf $3}'))"
	;;

backup)
	rm -f ${tempFile}

	${dockerExec} mysqldump ${defaultArgs} "${@:6}" > ${tempFile}
	if [ $? -ne 0 ]; then
		cat ${tempFile} >&2
		exit 1
	else
		set -e

		gzip < ${tempFile} > ${tempFile}.gzip
		jq -n \
			--argjson size $(wc -c ${tempFile}.gzip | awk '{printf $1}') \
			'{ size: $size }'

		duplicity full -v5 ${tempFile}.gzip ${storageUrl} >&2
	fi
	;;

restore)
	set -e
	>&2 duplicity -v5 --restore-time $2 ${storageUrl} ${tempFile}.gzip
	gunzip < ${tempFile}.gzip | ${dockerExec} mysql ${@:6} >&2
	;;

esac
